apps:
  - name        : "WatchDog"
    script      : "script/.jtchdogs"
    args        : ""
    cwd         : ""
    interpreter : "node"
    out_file    : "log/pm2_runtime_watch.log"
    error_file  : "log/pm2_runtime_watch.log"

  - name        : "RuntimeDownload"
    script      : "etc/daemon.download.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_runtime_download.log"
    error_file  : "log/pm2_runtime_download.log"

  - name        : "NightlyFinance"
    script      : "etc/daemon.finance.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_nightly_finance.log"
    error_file  : "log/pm2_nightly_finance.log"

  - name        : "WechatFlask"
    script      : "etc/daemon.wechatflask.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_wechat_flask.log"
    error_file  : "log/pm2_wechat_flask.log"

  - name        : "WechatQR"
    script      : "script/wechat_qr.js"
    args        : ""
    cwd         : ""
    interpreter : "node"
    out_file    : "log/pm2_wechat_qr.log"
    error_file  : "log/pm2_wechat_qr.log"

  - name        : "Redis"
    comment     : "run for windows"
    script      : "etc/daemon.redis.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_redis.log"
    error_file  : "log/pm2_redis.log"

  - name        : "Trade"
    script      : "etc/daemon.trade.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_trade.log"
    error_file  : "log/pm2_trade.log"

  # - name        : "Flower"
  #   script      : "etc/daemon.flower.sh"
  #   args        : ""
  #   cwd         : ""
  #   interpreter : "bash"
  #   out_file    : "log/pm2_flower.log"
  #   error_file  : "log/pm2_flower.log"
